### ISSUE TITLE
Secrets cause problem in output name

### ISSUE THREAD

**Issue by pilotak** [esphome/build-action#72]
when compiling and using secrets.yaml the `steps.esphome.outputs.name` will begin with `!secrets` 

```
Copied factory binary to: !secret ssid-esp32c3/!secret ssid-esp32c3.factory.bin
Copied OTA binary to: !secret ssid-esp32c3/!secret ssid-esp32c3.ota.bin
Copied ELF file to: !secret ssid-esp32c3/!secret ssid-esp32c3.elf
```

`device.yaml`
```yaml
substitutions:
  fw_ver: "v1.0.3"
  
esphome:
  name: test
  friendly_name: test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

logger:

ota:
  - platform: esphome

wifi:
  ap:
    ssid: !secret ssid
    password: !secret password
```

`secrets.yaml`
```yaml
ssid: "test"
password: "12345678"
```

You can see it in action https://github.com/pilotak/test/actions/runs/13375134420/job/37352565907
